"use client";
import { useMemo, useState } from "react";

type Order={id:string;customer:string;items:number;amount:number;status:string;payment:string};
const seedOrders:Order[]=[
{id:"PG-10001",customer:"Neha Sharma",items:2,amount:5298,status:"New",payment:"Pending"},
{id:"PG-10002",customer:"Pooja Jain",items:1,amount:3199,status:"Processing",payment:"Paid"},
{id:"PG-10003",customer:"Kavita Patidar",items:3,amount:6897,status:"Shipped",payment:"Paid"},
{id:"PG-10004",customer:"Ritu Agarwal",items:1,amount:1499,status:"Delivered",payment:"Paid"}
];
const money=(n:number)=>`₹${n.toLocaleString("en-IN")}`;
export default function Admin(){
 const [tab,setTab]=useState("Dashboard"),[orders,setOrders]=useState(seedOrders),[search,setSearch]=useState("");
 const filtered=useMemo(()=>orders.filter(o=>`${o.id} ${o.customer} ${o.status}`.toLowerCase().includes(search.toLowerCase())),[orders,search]);
 const stats=[['Orders',orders.length.toString(),'+12%'],['Sales',money(orders.reduce((s,o)=>s+o.amount,0)),'Today'],['Customers','128','+8 this week'],['Products','1,024','Catalog']];
 const nav=['Dashboard','Orders','Products','Inventory','Customers','Coupons','Delivery','Payments','Store settings'];
 return <div className="admin-shell"><aside className="admin-side"><div className="admin-brand"><div className="admin-mark">PG</div><div><b>PORWAL GHARANA</b><span>ADMIN PANEL</span></div></div><nav>{nav.map(n=><button key={n} className={tab===n?'on':''} onClick={()=>setTab(n)}>{n}</button>)}</nav><a href="/" className="store-link">← View store</a></aside>
 <main className="admin-main"><header className="admin-top"><div><span className="crumb">ADMIN /</span><h1>{tab}</h1></div><div className="admin-top-right"><span>Store: <b>Online</b></span><a href="/">Open storefront ↗</a><button className="avatar">PG</button></div></header>
 {tab==='Dashboard'&&<><section className="stat-grid">{stats.map(([a,b,c])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</section><section className="admin-grid"><div className="panel wide"><div className="panel-head"><div><h2>Recent orders</h2><p>Latest customer purchases</p></div><button onClick={()=>setTab('Orders')}>View all</button></div><OrdersTable orders={filtered.slice(0,5)} setOrders={setOrders}/></div><div className="panel"><div className="panel-head"><div><h2>Payment status</h2><p>Current order payments</p></div></div><div className="payment-box"><div><b>{orders.filter(o=>o.payment==='Paid').length}</b><span>Paid orders</span></div><div><b>{orders.filter(o=>o.payment==='Pending').length}</b><span>Pending</span></div><div><b>₹{orders.filter(o=>o.payment==='Paid').reduce((s,o)=>s+o.amount,0).toLocaleString('en-IN')}</b><span>Collected</span></div></div></div></section><section className="panel checklist"><div className="panel-head"><div><h2>Store controls</h2><p>Everything needed before going live</p></div></div>{[['Products','Add/edit products, SKU and stock'],['Coupons','Create percentage or fixed coupons'],['Delivery','Configure quantity-based shipping'],['Payments','Razorpay test mode → live mode']].map(x=><button key={x[0]} onClick={()=>setTab(x[0])}><b>{x[0]}</b><span>{x[1]}</span><i>→</i></button>)}</section></>}
 {tab!=='Dashboard'&&<section className="panel page-panel"><div className="panel-head"><div><h2>{tab}</h2><p>Admin controls for your Porwal Gharana store.</p></div><button className="primary" onClick={()=>alert(`${tab}: ready for database connection`)}>+ Add new</button></div>{tab==='Orders'?<OrdersTable orders={filtered} setOrders={setOrders}/>:<div className="placeholder-grid">{Array.from({length:6}).map((_,i)=><div className="control-card" key={i}><b>{['Catalog management','SKU & product codes','Stock levels','Customer records','Coupon rules','Configuration'][i]||tab}</b><span>Connect this section to the store database to manage it from here.</span><button>Configure →</button></div>)}</div>}</section>}
 </main></div>
}
function OrdersTable({orders,setOrders}:{orders:Order[];setOrders:React.Dispatch<React.SetStateAction<Order[]>>}){return <div className="table-wrap"><div className="table-search"><input placeholder="Search orders or customers" onChange={e=>{}}/><span>{orders.length} orders</span></div><table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.id}</b></td><td>{o.customer}</td><td>{o.items}</td><td><b>{money(o.amount)}</b></td><td><span className={`pill ${o.payment.toLowerCase()}`}>{o.payment}</span></td><td><select value={o.status} onChange={e=>setOrders(all=>all.map(x=>x.id===o.id?{...x,status:e.target.value}:x))}><option>New</option><option>Processing</option><option>Shipped</option><option>Delivered</option><option>Cancelled</option></select></td><td><button className="dots">•••</button></td></tr>)}</tbody></table></div>}
