"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase";
import styles from "./admin.module.css";

type Product={id:string;code:string;name:string;slug:string;price:number;mrp:number;stock:number;category_id:string|null;image_url:string|null;is_featured:boolean;is_active:boolean};
type Order={id:string;order_number:string;customer_name:string;customer_phone:string;total:number;payment_status:string;status:string;created_at:string};
type Category={id:string;name:string;slug:string;sort_order:number;is_active:boolean};
type Coupon={id:string;code:string;type:string;value:number;min_cart_value:number;max_discount:number|null;is_active:boolean;starts_at:string|null;ends_at:string|null};
type Customer={id:string;name:string;email:string|null;phone:string|null;city:string|null;created_at:string};
type Delivery={id:string;min_items:number;max_items:number|null;charge:number;free_shipping:boolean;is_active:boolean};
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
const tabs=["Dashboard","Orders","Products","Inventory","Customers","Coupons","Delivery","Categories","Store settings"];

export default function Admin(){
 const router=useRouter(); const [tab,setTab]=useState("Dashboard"); const [ready,setReady]=useState(false); const [userEmail,setUserEmail]=useState(""); const [error,setError]=useState("");
 const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[categories,setCategories]=useState<Category[]>([]),[coupons,setCoupons]=useState<Coupon[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[delivery,setDelivery]=useState<Delivery[]>([]); const [search,setSearch]=useState("");
 const [editing,setEditing]=useState<Product|null>(null); const [showProduct,setShowProduct]=useState(false); const [saving,setSaving]=useState(false);
 const load=async()=>{ if(!supabase)return; setError(""); const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace("/admin/login");return;} setUserEmail(user.email||""); const {data:profile}=await supabase.from("profiles").select("role,is_active").eq("id",user.id).single(); if(!profile||profile.role!=="admin"||!profile.is_active){await supabase.auth.signOut();router.replace("/admin/login");return;} const [p,o,c,cu,cl,d]=await Promise.all([supabase.from("products").select("*").order("created_at",{ascending:false}),supabase.from("orders").select("*").order("created_at",{ascending:false}),supabase.from("categories").select("*").order("sort_order"),supabase.from("coupons").select("*").order("created_at",{ascending:false}),supabase.from("customers").select("*").order("created_at",{ascending:false}),supabase.from("delivery_rules").select("*").order("min_items")]); setProducts(p.data||[]);setOrders(o.data||[]);setCategories(c.data||[]);setCoupons(cu.data||[]);setCustomers(cl.data||[]);setDelivery(d.data||[]); setReady(true); };
 useEffect(()=>{load()},[]);
 const filteredOrders=useMemo(()=>orders.filter(o=>`${o.order_number} ${o.customer_name} ${o.customer_phone} ${o.status}`.toLowerCase().includes(search.toLowerCase())),[orders,search]);
 const filteredProducts=useMemo(()=>products.filter(p=>`${p.code} ${p.name}`.toLowerCase().includes(search.toLowerCase())),[products,search]);
 async function signout(){await supabase?.auth.signOut();router.replace("/admin/login")}
 async function saveProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setSaving(true);const f=new FormData(e.currentTarget);const payload={code:String(f.get("code")),name:String(f.get("name")),slug:String(f.get("slug")),price:Number(f.get("price")),mrp:Number(f.get("mrp")),stock:Number(f.get("stock")),category_id:String(f.get("category_id"))||null,image_url:String(f.get("image_url"))||null,is_featured:f.get("featured")==="on",is_active:f.get("active")==="on"};const res=editing?await supabase.from("products").update(payload).eq("id",editing.id):await supabase.from("products").insert(payload);if(res.error)setError(res.error.message);else{setShowProduct(false);setEditing(null);await load()}setSaving(false)}
 async function deleteProduct(id:string){if(!supabase||!confirm("Delete this product?"))return;const {error:e}=await supabase.from("products").delete().eq("id",id);if(e)setError(e.message);else await load()}
 async function updateOrder(id:string,field:string,value:string){if(!supabase)return;const {error:e}=await supabase.from("orders").update({[field]:value,updated_at:new Date().toISOString()}).eq("id",id);if(e)setError(e.message);else setOrders(x=>x.map(o=>o.id===id?{...o,[field]:value}:o))}
 async function addCategory(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const {error:e2}=await supabase.from("categories").insert({name:String(f.get("name")),slug:String(f.get("slug")),sort_order:Number(f.get("sort_order")||0)});if(e2)setError(e2.message);else{e.currentTarget.reset();await load()}}
 async function addCoupon(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const {error:e2}=await supabase.from("coupons").insert({code:String(f.get("code")).toUpperCase(),type:String(f.get("type")),value:Number(f.get("value")),min_cart_value:Number(f.get("min_cart_value")||0),max_discount:f.get("max_discount")?Number(f.get("max_discount")):null,is_active:true});if(e2)setError(e2.message);else{e.currentTarget.reset();await load()}}
 async function saveDelivery(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const payload={min_items:Number(f.get("min_items")),max_items:f.get("max_items")?Number(f.get("max_items")):null,charge:Number(f.get("charge")),free_shipping:f.get("free_shipping")==="on",is_active:true};const id=String(f.get("id"));const res=id?await supabase.from("delivery_rules").update(payload).eq("id",id):await supabase.from("delivery_rules").insert(payload);if(res.error)setError(res.error.message);else await load()}
 if(!ready)return <div className={styles.loading}>Checking secure admin access…</div>;
 const sales=orders.filter(o=>o.payment_status==='paid').reduce((s,o)=>s+Number(o.total),0);
 return <div className={styles.shell}><aside className={styles.side}><div className={styles.brand}><div>PG</div><section><b>PORWAL GHARANA</b><span>ADMIN CONTROL</span></section></div><nav>{tabs.map(t=><button key={t} className={tab===t?styles.active:""} onClick={()=>{setTab(t);setSearch("")}}>{t}</button>)}</nav><a href="/">← View storefront</a><button className={styles.signout} onClick={signout}>Sign out</button></aside><main className={styles.main}><header className={styles.top}><div><small>SECURE ADMIN / {userEmail}</small><h1>{tab}</h1></div><div><span className={styles.online}>● Store online</span><a href="/">Open store ↗</a></div></header>{error&&<div className={styles.error}>{error}<button onClick={()=>setError("")}>×</button></div>}
 {tab==='Dashboard'&&<Dashboard orders={orders} products={products} customers={customers} sales={sales} setTab={setTab}/>} 
 {tab==='Orders'&&<Orders orders={filteredOrders} updateOrder={updateOrder} search={search} setSearch={setSearch}/>} 
 {tab==='Products'&&<Products products={filteredProducts} categories={categories} search={search} setSearch={setSearch} openNew={()=>{setEditing(null);setShowProduct(true)}} edit={p=>{setEditing(p);setShowProduct(true)}} remove={deleteProduct}/>} 
 {tab==='Inventory'&&<Inventory products={products} update={async(p,v)=>{if(!supabase)return;const {error:e}=await supabase.from('products').update({stock:v,updated_at:new Date().toISOString()}).eq('id',p.id);if(e)setError(e.message);else setProducts(x=>x.map(a=>a.id===p.id?{...a,stock:v}:a))}}/>}
 {tab==='Customers'&&<Customers customers={customers}/>} 
 {tab==='Coupons'&&<Coupons coupons={coupons} add={addCoupon} toggle={async id=>{const c=coupons.find(x=>x.id===id);if(!c||!supabase)return;await supabase.from('coupons').update({is_active:!c.is_active}).eq('id',id);await load()}}/>}
 {tab==='Delivery'&&<DeliveryPanel delivery={delivery} save={saveDelivery}/>} 
 {tab==='Categories'&&<Categories categories={categories} add={addCategory} toggle={async c=>{if(!supabase)return;await supabase.from('categories').update({is_active:!c.is_active}).eq('id',c.id);await load()}}/>}
 {tab==='Store settings'&&<Settings email={userEmail} />}
 </main>{showProduct&&<div className={styles.modal}><form className={styles.formCard} onSubmit={saveProduct}><div className={styles.formHead}><h2>{editing?"Edit product":"Add product"}</h2><button type="button" onClick={()=>setShowProduct(false)}>×</button></div><div className={styles.formGrid}><label>Product code<input name="code" defaultValue={editing?.code||"PWL-"} required/></label><label>Name<input name="name" defaultValue={editing?.name||""} required/></label><label>Slug<input name="slug" defaultValue={editing?.slug||""} required/></label><label>Category<select name="category_id" defaultValue={editing?.category_id||""}><option value="">Uncategorized</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Selling price<input name="price" type="number" min="0" defaultValue={editing?.price||0} required/></label><label>MRP<input name="mrp" type="number" min="0" defaultValue={editing?.mrp||0} required/></label><label>Stock<input name="stock" type="number" min="0" defaultValue={editing?.stock||0} required/></label><label>Image URL<input name="image_url" defaultValue={editing?.image_url||""} placeholder="https://…"/></label></div><div className={styles.checks}><label><input type="checkbox" name="featured" defaultChecked={editing?.is_featured}/> Featured</label><label><input type="checkbox" name="active" defaultChecked={editing?editing.is_active:true}/> Active</label></div><button className={styles.primary} disabled={saving}>{saving?"Saving…":"Save product"}</button></form></div>}</div>
}
function Dashboard({orders,products,customers,sales,setTab}:{orders:Order[];products:Product[];customers:Customer[];sales:number;setTab:(s:string)=>void}){return <><section className={styles.stats}>{[["Orders",orders.length,""],["Paid sales",money(sales),""],["Customers",customers.length,""],["Products",products.length,""],["Low stock",products.filter(p=>p.stock<5).length,"needs attention"]].map(x=><div key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]||"Live database"}</span></div>)}</section><section className={styles.grid2}><div className={styles.panel}><div className={styles.panelHead}><div><h2>Recent orders</h2><p>Real orders from Supabase</p></div><button onClick={()=>setTab('Orders')}>View all</button></div><OrdersMini orders={orders.slice(0,6)}/></div><div className={styles.panel}><div className={styles.panelHead}><div><h2>Store controls</h2><p>Manage the whole store here</p></div></div>{[["Products","Catalog, codes, prices, images, stock","Products"],["Inventory","Fast stock adjustments","Inventory"],["Coupons","Discount rules and limits","Coupons"],["Delivery","Quantity-based shipping","Delivery"],["Categories","Shop navigation","Categories"]].map(x=><button className={styles.control} key={x[0]} onClick={()=>setTab(x[2])}><b>{x[0]}</b><span>{x[1]}</span><i>→</i></button>)}</div></section></>}
function OrdersMini({orders}:{orders:Order[]}){return <div className={styles.miniList}>{orders.map(o=><div key={o.id}><b>{o.order_number}</b><span>{o.customer_name}</span><strong>{money(o.total)}</strong><em>{o.status}</em></div>)}</div>}
function Orders({orders,updateOrder,search,setSearch}:{orders:Order[];updateOrder:(id:string,f:string,v:string)=>void;search:string;setSearch:(s:string)=>void}){return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Orders</h2><p>Change fulfillment and payment status in real time.</p></div><input className={styles.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order, name or phone"/></div><div className={styles.table}><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Date</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.order_number}</b></td><td>{o.customer_name}<small>{o.customer_phone}</small></td><td><b>{money(o.total)}</b></td><td><select value={o.payment_status} onChange={e=>updateOrder(o.id,'payment_status',e.target.value)}><option>pending</option><option>paid</option><option>failed</option><option>refunded</option></select></td><td><select value={o.status} onChange={e=>updateOrder(o.id,'status',e.target.value)}><option>new</option><option>processing</option><option>shipped</option><option>delivered</option><option>cancelled</option></select></td><td>{new Date(o.created_at).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table></div></section>}
function Products({products,categories,search,setSearch,openNew,edit,remove}:{products:Product[];categories:Category[];search:string;setSearch:(s:string)=>void;openNew:()=>void;edit:(p:Product)=>void;remove:(id:string)=>void}){return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Products</h2><p>Build a 1000+ product catalog with SKU/product codes and stock.</p></div><div className={styles.headActions}><input className={styles.search} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search code or product"/><button className={styles.primary} onClick={openNew}>+ Add product</button></div></div><div className={styles.productTable}>{products.map(p=><article key={p.id}><div className={styles.thumb}>{p.image_url?<img src={p.image_url} alt=""/>:<span>{p.code.slice(-4)}</span>}</div><div><b>{p.name}</b><small>{p.code} · {categories.find(c=>c.id===p.category_id)?.name||'Uncategorized'}</small></div><strong>{money(p.price)}</strong><span>MRP {money(p.mrp)}</span><span className={p.stock<5?styles.low:""}>Stock {p.stock}</span><button onClick={()=>edit(p)}>Edit</button><button className={styles.dangerText} onClick={()=>remove(p.id)}>Delete</button></article>)}</div></section>}
function Inventory({products,update}:{products:Product[];update:(p:Product,v:number)=>void}){return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Inventory</h2><p>Quick stock control for every SKU.</p></div></div><div className={styles.inventory}>{products.map(p=><div key={p.id}><div><b>{p.name}</b><small>{p.code}</small></div><input type="number" min="0" defaultValue={p.stock} onBlur={e=>update(p,Number(e.target.value))}/></div>)}</div></section>}
function Customers({customers}:{customers:Customer[]}){return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Customers</h2><p>Customer records and contact details.</p></div></div><div className={styles.customerGrid}>{customers.map(c=><div key={c.id}><b>{c.name}</b><span>{c.phone||'No phone'}</span><span>{c.email||'No email'}</span><span>{c.city||'—'}</span></div>)}</div></section>}
function Coupons({coupons,add,toggle}:{coupons:Coupon[];add:(e:FormEvent<HTMLFormElement>)=>void;toggle:(id:string)=>void}){return <section className={styles.grid2}><form className={styles.panel} onSubmit={add}><h2>Create coupon</h2><div className={styles.formGrid}><label>Code<input name="code" placeholder="PG10" required/></label><label>Type<select name="type"><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Value<input name="value" type="number" min="0" required/></label><label>Min cart value<input name="min_cart_value" type="number" min="0" defaultValue="0"/></label><label>Max discount<input name="max_discount" type="number" min="0"/></label></div><button className={styles.primary}>Create coupon</button></form><div className={styles.panel}><h2>Coupons</h2><div className={styles.list}>{coupons.map(c=><div key={c.id}><b>{c.code}</b><span>{c.type==='percentage'?`${c.value}%`:money(c.value)} · min {money(c.min_cart_value)}</span><button onClick={()=>toggle(c.id)}>{c.is_active?'Active':'Disabled'}</button></div>)}</div></div></section>}
function DeliveryPanel({delivery,save}:{delivery:Delivery[];save:(e:FormEvent<HTMLFormElement>)=>void}){return <section className={styles.panel}><div className={styles.panelHead}><div><h2>Delivery charges</h2><p>Quantity-based shipping rules.</p></div></div>{delivery.map(d=><form className={styles.rule} key={d.id} onSubmit={save}><input type="hidden" name="id" value={d.id}/><label>Min items<input name="min_items" type="number" defaultValue={d.min_items}/></label><label>Max items<input name="max_items" type="number" defaultValue={d.max_items??""}/></label><label>Charge<input name="charge" type="number" defaultValue={d.charge}/></label><label className={styles.inlineCheck}><input name="free_shipping" type="checkbox" defaultChecked={d.free_shipping}/> Free</label><button className={styles.primary}>Save</button></form>)}</section>}
function Categories({categories,add,toggle}:{categories:Category[];add:(e:FormEvent<HTMLFormElement>)=>void;toggle:(c:Category)=>void}){return <section className={styles.grid2}><form className={styles.panel} onSubmit={add}><h2>Add category</h2><div className={styles.formGrid}><label>Name<input name="name" required placeholder="Banarasi"/></label><label>Slug<input name="slug" required placeholder="banarasi"/></label><label>Sort order<input name="sort_order" type="number" defaultValue="0"/></label></div><button className={styles.primary}>Add category</button></form><div className={styles.panel}><h2>Categories</h2><div className={styles.list}>{categories.map(c=><div key={c.id}><b>{c.name}</b><span>/{c.slug}</span><button onClick={()=>toggle(c)}>{c.is_active?'Active':'Disabled'}</button></div>)}</div></div></section>}
function Settings({email}:{email:string}){return <section className={styles.panel}><h2>Store settings</h2><p className={styles.muted}>Admin account: {email}</p><div className={styles.settingsCards}><div><b>Authentication</b><span>Supabase email/password sign-in is used for this panel.</span></div><div><b>Catalog</b><span>Products, categories, SKU codes, prices and stock are database-backed.</span></div><div><b>Payments</b><span>Fake test payment is next. Razorpay is intentionally kept for the final phase.</span></div><div><b>WhatsApp</b><span>WhatsApp integration is intentionally kept for the final phase.</span></div></div></section>}
