"use client";
import Script from "next/script";
import {useEffect,useMemo,useState} from "react";
import s from "./checkout.module.css";

type Item={name:string;price:number;qty:number};
const demoItems:Item[]=[{name:"Kashvi Silk Saree",price:2499,qty:1}];
const money=(n:number)=>`₹${n.toLocaleString("en-IN")}`;
export default function Checkout(){
 const [items,setItems]=useState<Item[]>(demoItems),[coupon,setCoupon]=useState(""),[couponMsg,setCouponMsg]=useState(""),[busy,setBusy]=useState(false),[paid,setPaid]=useState(false);
 const [form,setForm]=useState({name:"",phone:"",address:"",city:"Mandsaur",state:"Madhya Pradesh",pin:""});
 useEffect(()=>{try{const raw=localStorage.getItem("porwal-cart");if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed)&&parsed.length)setItems(parsed)}}catch{}} ,[]);
 const subtotal=useMemo(()=>items.reduce((x,i)=>x+i.price*i.qty,0),[items]);
 const discount=coupon.trim().toUpperCase()==="PG10"?Math.min(Math.round(subtotal*.1),500):0;
 const delivery=items.reduce((x,i)=>x+i.qty,0)>=3?0:99;
 const total=Math.max(0,subtotal-discount+delivery);
 const applyCoupon=()=>setCouponMsg(coupon.trim().toUpperCase()==="PG10"?"Coupon applied — 10% off":"Demo coupon: PG10");
 const pay=async()=>{if(!form.name||!form.phone||!form.address||!form.pin){alert("Please complete your delivery details.");return}setBusy(true);try{const r=await fetch("/api/payment/create-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount:total,items,customer:form})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Payment setup failed");if(!(window as any).Razorpay)throw new Error("Razorpay checkout is still loading. Try again.");const rz=new (window as any).Razorpay({key:data.key,amount:data.amount,currency:"INR",name:"PORWAL GHARANA",description:"Saree order",order_id:data.orderId,prefill:{name:form.name,contact:form.phone},theme:{color:"#142b4d"},handler:async(response:any)=>{const vr=await fetch("/api/payment/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...response,amount:total,customer:form,items})});if(vr.ok)setPaid(true);else alert("Payment verification failed.")}});rz.open()}catch(e:any){alert(e.message||"Could not start payment. Add Razorpay TEST keys first.")}finally{setBusy(false)}};
 if(paid)return <main className={s.success}><div className={s.successCard}><div className={s.mark}>✓</div><h1>Payment received</h1><p>Your Porwal Gharana order has been confirmed.</p><a href="/">Continue shopping →</a></div></main>;
 return <main className={s.page}><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><header className={s.head}><a href="/" className={s.brand}><span>PG</span><b>PORWAL GHARANA</b></a><div>🔒 Secure checkout</div></header><div className={s.layout}><section className={s.card}><div className={s.step}><span>1</span><div><h2>Delivery address</h2><p>Where should we deliver your sarees?</p></div></div><div className={s.form}><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Customer name"/></label><label>Mobile number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="10 digit mobile number"/></label><label className={s.full}>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="House / street / area"/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>PIN code<input value={form.pin} onChange={e=>setForm({...form,pin:e.target.value})} placeholder="458001"/></label></div><div className={`${s.step} ${s.second}`}><span>2</span><div><h2>Payment</h2><p>Razorpay TEST mode is ready.</p></div></div><button className={s.pay} disabled={busy} onClick={pay}>{busy?"Starting secure payment…":`Pay ${money(total)}`}</button><p className={s.note}>TEST MODE only. Add Razorpay TEST keys in Vercel. No real money is collected until live keys are configured.</p></section><aside className={`${s.card} ${s.summary}`}><h2>Order summary</h2>{items.map((i,n)=><div className={s.item} key={n}><div><b>{i.name}</b><span>Qty {i.qty}</span></div><strong>{money(i.price*i.qty)}</strong></div>)}<div className={s.coupon}><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code"/><button onClick={applyCoupon}>Apply</button></div>{couponMsg&&<small className={s.couponMsg}>{couponMsg}</small>}<div className={s.totals}><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Discount</span><b>-{money(discount)}</b></div><div><span>Delivery</span><b>{delivery?money(delivery):"FREE"}</b></div><div className={s.grand}><span>Total</span><b>{money(total)}</b></div></div></aside></div></main>}
