"use client";
import Script from "next/script";
import {useEffect,useMemo,useState} from "react";

type Item={name:string;price:number;qty:number};
const demoItems:Item[]=[{name:"Kashvi Silk Saree",price:2499,qty:1}];
const money=(n:number)=>`₹${n.toLocaleString("en-IN")}`;
export default function Checkout(){
 const [items,setItems]=useState<Item[]>(demoItems),[coupon,setCoupon]=useState(""),[couponMsg,setCouponMsg]=useState(""),[busy,setBusy]=useState(false),[paid,setPaid]=useState(false);
 const [form,setForm]=useState({name:"",phone:"",address:"",city:"Mandsaur",state:"Madhya Pradesh",pin:""});
 useEffect(()=>{try{const raw=localStorage.getItem("porwal-cart");if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed)&&parsed.length)setItems(parsed)}}catch{}},[]);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.price*i.qty,0),[items]);
 const discount=coupon.trim().toUpperCase()==="PG10"?Math.min(Math.round(subtotal*.1),500):0;
 const delivery=items.reduce((s,i)=>s+i.qty,0)>=3?0:99;
 const total=Math.max(0,subtotal-discount+delivery);
 const applyCoupon=()=>setCouponMsg(coupon.trim().toUpperCase()==="PG10"?"Coupon applied — 10% off":"Try PG10 for a demo 10% discount");
 const pay=async()=>{if(!form.name||!form.phone||!form.address||!form.pin){alert("Please complete your delivery details.");return}setBusy(true);try{const r=await fetch("/api/payment/create-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount:total,items,customer:form})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Payment setup failed");if(!(window as any).Razorpay)throw new Error("Razorpay checkout is still loading. Please try again.");const rz=new (window as any).Razorpay({key:data.key,amount:data.amount,currency:"INR",name:"PORWAL GHARANA",description:"Saree order",order_id:data.orderId,prefill:{name:form.name,contact:form.phone},theme:{color:"#142b4d"},handler:async(response:any)=>{const vr=await fetch("/api/payment/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...response,amount:total,customer:form,items})});if(vr.ok)setPaid(true);else alert("Payment verification failed. Please contact the store.")}});rz.open()}catch(e:any){alert(e.message||"Could not start payment. Add Razorpay test keys in Vercel first.")}finally{setBusy(false)}};
 if(paid)return <main className="checkout-page"><div className="success-card"><div className="success-mark">✓</div><h1>Payment received</h1><p>Your Porwal Gharana order has been confirmed.</p><a href="/">Continue shopping →</a></div></main>;
 return <main className="checkout-page"><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"/><header className="checkout-head"><a href="/" className="checkout-brand"><span>PG</span><b>PORWAL GHARANA</b></a><div>Secure checkout</div></header><div className="checkout-layout"><section className="checkout-card"><div className="step"><span>1</span><div><h2>Delivery address</h2><p>Where should we deliver your sarees?</p></div></div><div className="form-grid"><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Customer name"/></label><label>Mobile number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="10 digit mobile number"/></label><label className="full">Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="House / street / area"/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>PIN code<input value={form.pin} onChange={e=>setForm({...form,pin:e.target.value})} placeholder="458001"/></label></div><div className="step second"><span>2</span><div><h2>Payment</h2><p>Razorpay TEST mode is ready for integration.</p></div></div><button className="pay-button" disabled={busy} onClick={pay}>{busy?"Starting secure payment…":`Pay ${money(total)}`}</button><p className="test-note">TEST MODE: use Razorpay test credentials only. No real money should be collected until live keys and production verification are configured.</p></section><aside className="checkout-card summary-card"><h2>Order summary</h2>{items.map((i,n)=><div className="summary-item" key={n}><div><b>{i.name}</b><span>Qty {i.qty}</span></div><strong>{money(i.price*i.qty)}</strong></div>)}<div className="coupon"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code"/><button onClick={applyCoupon}>Apply</button></div>{couponMsg&&<small className="coupon-msg">{couponMsg}</small>}<div className="totals"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Discount</span><b>-{money(discount)}</b></div><div><span>Delivery</span><b>{delivery?money(delivery):"FREE"}</b></div><div className="grand"><span>Total</span><b>{money(total)}</b></div></div></aside></div></main>}
