"use client";
import {useEffect,useMemo,useState} from "react";
import {supabase} from "../../lib/supabase";
import s from "./checkout.module.css";

type Item={id?:string;code:string;name:string;price:number;qty?:number;stock?:number};
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
export default function Checkout(){
 const [items,setItems]=useState<Item[]>([]),[coupon,setCoupon]=useState(""),[couponMsg,setCouponMsg]=useState(""),[busy,setBusy]=useState(false),[paid,setPaid]=useState(false),[orderNumber,setOrderNumber]=useState("");
 const [form,setForm]=useState({name:"",phone:"",address:"",city:"Mandsaur",pin:""}); const [delivery,setDelivery]=useState(99);
 useEffect(()=>{try{const raw=localStorage.getItem("porwal-cart");const parsed=raw?JSON.parse(raw):[];if(Array.isArray(parsed))setItems(parsed)}catch{};(async()=>{if(!supabase)return;const {data}=await supabase.from('delivery_rules').select('*').eq('is_active',true).order('min_items');if(data?.length)setDelivery(Number(data.find((x:any)=>x.min_items<=1)?.charge??99)})()},[]);
 const subtotal=useMemo(()=>items.reduce((x,i)=>x+i.price*(i.qty||1),0),[items]); const discount=coupon.trim().toUpperCase()==="PG10"?Math.min(Math.round(subtotal*.1),500):0; const count=items.reduce((x,i)=>x+(i.qty||1),0); const ship=count>=3?0:delivery; const total=Math.max(0,subtotal-discount+ship);
 const applyCoupon=()=>setCouponMsg(coupon.trim().toUpperCase()==="PG10"?"Coupon applied — 10% off":"Demo coupon: PG10");
 const testPay=async()=>{if(!form.name||!form.phone||!form.address||!form.pin){alert("Please complete your delivery details.");return}if(!items.length){alert("Your cart is empty.");return}if(!supabase){alert("Supabase is not configured yet.");return}setBusy(true);const payload=items.map(i=>({id:i.id,code:i.code,name:i.name,price:i.price,qty:i.qty||1}));const {data,error}=await supabase.rpc('create_test_order',{p_customer:form,p_items:payload,p_subtotal:subtotal,p_product_discount:0,p_coupon_code:discount?coupon.trim().toUpperCase():null,p_coupon_discount:discount,p_delivery_charge:ship,p_total:total});if(error){alert(error.message);setBusy(false);return}setOrderNumber(data?.[0]?.order_number||"");setPaid(true);localStorage.removeItem("porwal-cart");setBusy(false)};
 if(paid)return <main className={s.success}><div className={s.successCard}><div className={s.mark}>✓</div><h1>Test payment successful</h1><p>Your fake test payment was recorded and the order is now visible in the admin panel.</p>{orderNumber&&<strong>Order {orderNumber}</strong>}<a href="/">Continue shopping →</a></div></main>;
 return <main className={s.page}><header className={s.head}><a href="/" className={s.brand}><span>PG</span><b>PORWAL GHARANA</b></a><div>🧪 TEST CHECKOUT</div></header><div className={s.layout}><section className={s.card}><div className={s.step}><span>1</span><div><h2>Delivery address</h2><p>Where should we deliver your sarees?</p></div></div><div className={s.form}><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Customer name"/></label><label>Mobile number<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="10 digit mobile number"/></label><label className={s.full}>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="House / street / area"/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>PIN code<input value={form.pin} onChange={e=>setForm({...form,pin:e.target.value})} placeholder="458001"/></label></div><div className={`${s.step} ${s.second}`}><span>2</span><div><h2>Fake test payment</h2><p>No Razorpay yet. This button simulates a successful payment and creates a real test order in Supabase.</p></div></div><button className={s.pay} disabled={busy} onClick={testPay}>{busy?"Creating test order…":`Complete test payment · ${money(total)}`}</button><p className={s.note}>TEST ONLY — no money is charged. Razorpay will be added in the final payment phase.</p></section><aside className={`${s.card} ${s.summary}`}><h2>Order summary</h2>{items.map((i,n)=><div className={s.item} key={n}><div><b>{i.name}</b><span>Qty {i.qty||1} · {i.code}</span></div><strong>{money(i.price*(i.qty||1))}</strong></div>)}<div className={s.coupon}><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code"/><button onClick={applyCoupon}>Apply</button></div>{couponMsg&&<small className={s.couponMsg}>{couponMsg}</small>}<div className={s.totals}><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Discount</span><b>-{money(discount)}</b></div><div><span>Delivery</span><b>{ship?money(ship):"FREE"}</b></div><div className={s.grand}><span>Total</span><b>{money(total)}</b></div></div></aside></div></main>;
}
